# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "${SHOPIFY_API_KEY}"
name = "sticky-cart-firebase"
application_url = "${SHOPIFY_APP_URL}"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dimestore-test.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "${SHOPIFY_APP_URL}/auth/callback",
  "${SHOPIFY_APP_URL}/auth/shopify/callback"
]

[app_proxy]
url = "${SHOPIFY_APP_URL}/proxy"
subpath = "cart-drawer"
prefix = "tools"

[pos]
embedded = false
